name: Trigger Jenkins Job on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins job
        env:
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_URL: ${{ vars.JENKINS_URL }}
        run: |
          echo "Durga of MY_VARIABLE: $JENKINS_URL"
             # Trigger Jenkins job and get queue item number
          queue_url=$(curl -X POST $JENKINS_URL/job/test/build \
            --user durga:$JENKINS_API_TOKEN) 
          
          # Extract queue item number
          queue_item=$(basename "$queue_url")

          echo "$queue_item"

          status=""
          while [ "$status" != "SUCCESS" ] && [ "$status" != "FAILURE" ]; do
            status=$(curl -s -X GET "$JENKINS_URL/queue/item/$queue_item/api/json" \
              --user durga:$JENKINS_API_TOKEN | jq -r .executable.result)
            sleep 5
          done
