name: Trigger Jenkins Job on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: jabbukka/jenkins-trigger@main
        with:
          url: ${{ vars.JENKINS_URL }}
          job_name: "test"
          user_name: "durga"
          api_token: ${{ secrets.JENKINS_API_TOKEN }}
          wait: "true"
          timeout: "1000"
