# This is a basic workflow to help you get started with Actions

name: Trigger Jenkins Job on Pull Request

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins job
        env:
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST https://66fcb0e9fb53496894b8ba363b676c3e-2887499781-8080-host12nc.environments.katacoda.com/job/test/build \
          --user admin:$JENKINS_API_TOKEN \

